MTAdmin.Web/Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;
using MTClient.Application.Services.Interfaces;

namespace MTAdmin.Web.Controllers
{    
    public class AboutUsController : ClientBaseController
    {
        private readonly IAboutUsService _service;
        public AboutUsController(IAboutUsService service)
        {
            _service = service;
        }
        [Route("about-us")]
        public async Task<IActionResult> Index()
        {
            var result = await _service.GetAboutUsMetaData();
            AddMetaData(result.Data);
            return View();
        }
    }
}

MTAdmin.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MTAdmin.Shared.Enums;
using MTAdmin.Shared.ViewModels.Client;
using MTClient.Application.Services.Interfaces;

namespace MTAdmin.Web.Controllers
{
    public class CategoryController : ClientBaseController
    {
        private readonly ICategoryService _service;
        private readonly ITemplateService _templateService;
        public CategoryController(ICategoryService service,ITemplateService templateService)
        {
            _service = service;
            _templateService = templateService;
        }
        [Route("{filter?}/meme-template-categories")]
        public async Task<IActionResult> Index(string filter = "trending")
        {
            var @params = new CategoryParams
            {
                FilterBy = CategoryFilterEnum.trending
            };
            if (!string.IsNullOrWhiteSpace(filter))
            {
                if(Enum.TryParse(filter, out CategoryFilterEnum filterBy))
                {
                    if (Enum.IsDefined(filterBy))
                    {
                        @params.FilterBy = filterBy;
                    }                    
                }
                else
                {
                    return RedirectToAction(nameof(Index), new { filter = "trending" });
                }
            }
            var result = await _service.GetCategories(@params);
            var metaTags = await _service.GetCategoryMetaData();
            AddMetaData(metaTags.Data);
            return View(result.Data);
        }
        [Route("category/{id}/{filter?}/{slug}-meme-templats")]
        public async Task<IActionResult> Detail(int id,string slug, string filter = null)
        {            
            var @params = new TemplateParams()
            {
                Query = null,
                CategoryId = id,
                FilterBy = FilterByEnum.latest
            };
            if (!string.IsNullOrWhiteSpace(filter) && Enum.TryParse(filter, out FilterByEnum filterBy))
            {
                if (Enum.IsDefined(filterBy))
                {
                    @params.FilterBy = filterBy;
                }
            }
            if (@params.CategoryId <= 0 || !Enum.IsDefined(@params.FilterBy))
            {
                return View();
            }
            await _service.SaveCatogyPostViewState(id);
            var result = await _templateService.GetTemplates(@params);
            var metaTags = await _service.GetCategoryMetaDataById(@params.CategoryId);
            if (result.IsSuccess)
            {
                result.Data.CategorySlug = slug;
                int i = 0;
                while (i < result.Data.TemplateList.Items.Count)
                {
                    result.Data.TemplateList.Items[i].TemplateType = GetFileContentType(result.Data.TemplateList.Items[i].FileName);
                    i++;
                }
            }
            if (metaTags.IsSuccess)
            {
                AddMetaData(metaTags.Data);
            }
            return View(result.Data);
        }
        [HttpPost]
        [Route("GetCategories")]
        public async Task<IActionResult> GetCategories(CategoryParams @params)
        {
            var result = await _service.GetCategories(@params);
            return PartialView("~/Views/Category/_CategoryList.cshtml", result.Data.CategoryList);
        }        
    }
}

MTAdmin.Web/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using MTAdmin.Shared.ViewModels.Client;
using MTClient.Application.Services.Interfaces;

namespace MTAdmin.Web.Controllers
{
    public class ContactController : ClientBaseController
    {
        private readonly IContactService _service;
        private readonly IHttpContextAccessor _contextAccessor;
        public ContactController(IContactService service, IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
            _service = service;
        }
        [Route("contact")]
        public IActionResult Index()
        {
            //var metaTags = await _service.GetContactPageMetaData();
            //AddMetaData(metaTags.Data);
            return View(new ContactVM());
        }
        [HttpPost]
        [Route("thank-you")]
        public async Task<IActionResult> ThankYou(ContactVM vm)
        {
            if (ModelState.IsValid)
            {
                vm.IPAddress = _contextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();
                //var metaTags = await _service.GetContactPageMetaData();
                //AddMetaData(metaTags.Data);
                await _service.AddContact(vm);              
            }
            return View();
        }
    }
}

MTAdmin.Web/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;

namespace MTAdmin.Web.Controllers
{
    public class TagsController : ClientBaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MTAdmin.Web/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Hello </strong> Memer.
</footer>

MTAdmin.Web/Views/Shared/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-dark navbar-light">
    <ul class="navbar-nav">
        <!--TODO: show only on mobile view-->
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li> 
        @* <li class="nav-item d-none d-sm-inline-block">
        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
        </li> *@
    </ul>

    <ul class="navbar-nav ml-auto">
        @* <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block" style="display: none;">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li> *@
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
</nav>

MTAdmin.Web/Views/Shared/_Layout.cshtml
@using MTAdmin.Web.ViewComponents
<!DOCTYPE html>
<html lang="en">
<head>    
    @(await Component.InvokeAsync(nameof(MetaTags)))
    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">*@
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" asp-append-version="true"/>    
    <link rel="stylesheet" href="~/admin-lte/css/adminlte.min.css" asp-append-version="true"/>  
    <link rel="stylesheet" href="~/plugins/select2/css/select2.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link href="https://vjs.zencdn.net/8.6.1/video-js.css" rel="stylesheet" asp-append-version="true" />
    <style>
        .validation-summary-valid span {
            display: none;
        }

        .validation-summary-errors {
            color: red
        }

        .blur-up {
            -webkit-filter: blur(5px);
            filter: blur(5px);
            transition: filter 400ms, -webkit-filter 400ms;
        }

            .blur-up.lazyloaded {
                -webkit-filter: blur(0);
                filter: blur(0);
            }

        .dark-mode .select2-container--bootstrap4 .select2-selection--multiple .select2-selection__choice {
            color: #181717;
        }
    </style>
    @await RenderSectionAsync("Styles", required: false)
</head>
<!--sidebar-mini-->
<body class="sidebar-mini layout-fixed dark-mode">
    <div class="wrapper">
        @* <environment names="Production">
            <cache>
                @await Html.PartialAsync("_Header.cshtml")
                @(await Component.InvokeAsync(nameof(SideBar)))
            </cache>            
        </environment>    *@     
        <environment names="Development">
            @await Html.PartialAsync("_Header.cshtml")
            @(await Component.InvokeAsync(nameof(SideBar)))
        </environment>
        <div class="content-wrapper">
            @* @await Html.PartialAsync("_BreadCrumb.cshtml") *@
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            @* @await Component.InvokeAsync(nameof(PageHeader)) *@
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                @* @(await Component.InvokeAsync(nameof(Breadcrumb))) *@
                            </ol>
                        </div>
                        <br/>                        
                    </div>
                </div>
            </section>
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </section>
        </div>
        <environment names="Development">
            @await Html.PartialAsync("_Footer.cshtml")
        </environment>        
@*         <environment names="Production">
            <cache>
                @await Html.PartialAsync("_Footer.cshtml")
            </cache>
        </environment> *@
    </div>
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/admin-lte/js/adminlte.min.js" asp-append-version="true"></script>
    <script src="~/plugins/select2/js/select2.full.min.js" asp-append-version="true"></script> 
    <script src="~/lib/lazysizes/lazysizes.min.js" asp-append-version="true" async=""></script>
    <script src="https://vjs.zencdn.net/8.6.1/video.min.js" asp-append-version="true"></script>
    <script src="~/js/s.js"></script>
    <script>
        window.HELP_IMPROVE_VIDEOJS = false;
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        });        
        // $(".video-js").each(function (videoIndex) {

        //     var videoId = $(this).attr("id");

        //     videojs(videoId).ready(function () {
        //         this.on("play", function (e) {
        //             //pause other video
        //             $(".video-js").each(function (index) {
        //                 if (videoIndex !== index) {
        //                     this.player.pause();
        //                 }
        //             });
        //         });

        //     });
        // });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<!-- change div tag to section in content-header and content-->

MTAdmin.Web/Views/Shared/_SidebarNav.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="index3.html" class="brand-link">
        <span class="brand-text font-weight-light">Meme Templates</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="/" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            The Meme Tempalates
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Category")" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            Categories
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Tags")" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            Tags
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","AboutUs")" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            About Us
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Contact")" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            Contact
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","Disclaimer")" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            Disclaimer
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index","PrivacyPolicy")" class="nav-link">
                        <i class="nav-icon far fa-calendar-alt"></i>
                        <p>
                            Privacy Policy
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>