MTAdmin.Web/Areas/Archone/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MTAdmin.Infra.Identity.Entities;
using MTAdmin.Shared.ViewModels;

namespace MTAdmin.Web.Areas.Archone.Controllers
{
    [Area("Archone")]
    public class AuthController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public AuthController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager )
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            await _signInManager.SignOutAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginVm vm)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(vm.Email, vm.Password, false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                if (result.IsLockedOut)
                {
                    return View("Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(vm);
                }
            }            
            return View(vm);
        }
        
        public async Task<IActionResult> LogOff()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

MTAdmin.Web/Areas/Archone/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using MTAdmin.Application.Services.Interfaces;
using MTAdmin.Shared.ViewModels;
using NToastNotify;

namespace MTAdmin.Web.Areas.Archone.Controllers
{
    public class TagController : BaseController
    {
        private readonly ITagService _service;

        public TagController(ITagService service, IToastNotification notification) : base(notification) => _service = service;
        public async Task<IActionResult> Index(string s, int page = 1)
        {
            ViewData["s"] = s;
            var parameters = new TagParameters()
            {
                Query = s,
                PageNumber = page
            };
            var result = await _service.GetTags(parameters);
            ShowMessage(result);
            if (result.IsSuccess)
            {
                return View(result.Data);
            }
            return View();
        }

        public IActionResult Add()
        {
            return View(new CreateTagVM() { IsActive = true });
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateTagVM vm)
        {
            if (ModelState.IsValid)
            {
                var result = await _service.CreateTag(vm);
                ShowMessage(result);
                if (result.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(vm);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var result = await _service.GetTagById(Id);
            ShowMessage(result);
            if (result.IsSuccess)
            {
                return View(result.Data);
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TagVM vm)
        {
            if (ModelState.IsValid)
            {
                var result = await _service.UpdateTag(vm);
                ShowMessage(result);
                if (result.IsSuccess && result.Data > 0)
                {
                    //_toastNotification.AddSuccessToastMessage("Tag Edited");
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Ex.Message);
            }
            return View(vm);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var result = await _service.DeleteTag(0);
            ShowMessage(result);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> ActiveInActive(int Id)
        {
            var result = await _service.ActiveInActive(Id);
            ShowMessage(result);
            return RedirectToAction(nameof(Index));
        }
    }
}

MTAdmin.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MTAdmin.Shared.Enums;
using MTAdmin.Shared.ViewModels.Client;
using MTClient.Application.Services.Interfaces;

namespace MTAdmin.Web.Controllers
{
    public class CategoryController : ClientBaseController
    {
        private readonly ICategoryService _service;
        private readonly ITemplateService _templateService;
        public CategoryController(ICategoryService service,ITemplateService templateService)
        {
            _service = service;
            _templateService = templateService;
        }
        [Route("{filter?}/meme-template-categories")]
        public async Task<IActionResult> Index(string filter = "trending")
        {
            var @params = new CategoryParams
            {
                FilterBy = CategoryFilterEnum.trending
            };
            if (!string.IsNullOrWhiteSpace(filter))
            {
                if(Enum.TryParse(filter, out CategoryFilterEnum filterBy))
                {
                    if (Enum.IsDefined(filterBy))
                    {
                        @params.FilterBy = filterBy;
                    }                    
                }
                else
                {
                    return RedirectToAction(nameof(Index), new { filter = "trending" });
                }
            }
            var result = await _service.GetCategories(@params);
            var metaTags = await _service.GetCategoryMetaData();
            AddMetaData(metaTags.Data);
            return View(result.Data);
        }
        [Route("category/{id}/{filter?}/{slug}-meme-templats")]
        public async Task<IActionResult> Detail(int id,string slug, string filter = null)
        {            
            var @params = new TemplateParams()
            {
                Query = null,
                CategoryId = id,
                FilterBy = FilterByEnum.latest
            };
            if (!string.IsNullOrWhiteSpace(filter) && Enum.TryParse(filter, out FilterByEnum filterBy))
            {
                if (Enum.IsDefined(filterBy))
                {
                    @params.FilterBy = filterBy;
                }
            }
            if (@params.CategoryId <= 0 || !Enum.IsDefined(@params.FilterBy))
            {
                return View();
            }
            await _service.SaveCatogyPostViewState(id);
            var result = await _templateService.GetTemplates(@params);
            var metaTags = await _service.GetCategoryMetaDataById(@params.CategoryId);
            if (result.IsSuccess)
            {
                result.Data.CategorySlug = slug;
                int i = 0;
                while (i < result.Data.TemplateList.Items.Count)
                {
                    result.Data.TemplateList.Items[i].TemplateType = GetFileContentType(result.Data.TemplateList.Items[i].FileName);
                    i++;
                }
            }
            if (metaTags.IsSuccess)
            {
                AddMetaData(metaTags.Data);
            }
            return View(result.Data);
        }
        [HttpPost]
        [Route("GetCategories")]
        public async Task<IActionResult> GetCategories(CategoryParams @params)
        {
            var result = await _service.GetCategories(@params);
            return PartialView("~/Views/Category/_CategoryList.cshtml", result.Data.CategoryList);
        }        
    }
}

MTAdmin.Web/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using MTAdmin.Shared.ViewModels.Client;
using MTClient.Application.Services.Interfaces;

namespace MTAdmin.Web.Controllers
{
    public class ContactController : ClientBaseController
    {
        private readonly IContactService _service;
        private readonly IHttpContextAccessor _contextAccessor;
        public ContactController(IContactService service, IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
            _service = service;
        }
        [Route("contact")]
        public IActionResult Index()
        {
            //var metaTags = await _service.GetContactPageMetaData();
            //AddMetaData(metaTags.Data);
            return View(new ContactVM());
        }
        [HttpPost]
        [Route("thank-you")]
        public async Task<IActionResult> ThankYou(ContactVM vm)
        {
            if (ModelState.IsValid)
            {
                vm.IPAddress = _contextAccessor.HttpContext.Connection.RemoteIpAddress.ToString();
                //var metaTags = await _service.GetContactPageMetaData();
                //AddMetaData(metaTags.Data);
                await _service.AddContact(vm);              
            }
            return View();
        }
    }
}

MTAdmin.Web/Areas/Archone/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Hello </strong> Admin.
</footer>

MTAdmin.Web/Areas/Archone/Views/Shared/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">

    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a asp-controller="Auth" asp-action="LogOff" class="nav-link">
                <i class="fas fa-sign-out-alt"></i>
            </a>
        </li>
    </ul>
</nav>

MTAdmin.Web/Areas/Archone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin</title>

    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">*@
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/admin-lte/css/adminlte.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/plugins/select2/css/select2.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/plugins/toastr/toastr.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/plugins/bs-stepper/css/bs-stepper.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/plugins/sweetalert2/sweetalert2.css" asp-append-version="true"/>
    <style>
        .validation-summary-valid span {
            display: none;
        }

        .validation-summary-errors {
            color: red
        }
    </style>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body class="hold-transition sidebar-mini sidebar-collapse">
    <div class="wrapper">
        @await Html.PartialAsync("_Header.cshtml")
        @* @await Html.PartialAsync("_SidebarNav.cshtml") *@
        @(await Component.InvokeAsync(nameof(Sidebar)))
        <div class="content-wrapper">
            @*@await Html.PartialAsync("_BreadCrumb.cshtml")*@
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            @* @await Component.InvokeAsync(nameof(PageHeader)) *@
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                @* @(await Component.InvokeAsync(nameof(Breadcrumb))) *@
                            </ol>
                        </div>
                        <br/>
                        @await Component.InvokeAsync("NToastNotify")
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
        @await Html.PartialAsync("_Footer.cshtml")
    </div>
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/admin-lte/js/adminlte.min.js" asp-append-version="true" async></script>
    <script src="~/plugins/select2/js/select2.full.min.js" asp-append-version="true" async></script>
    @* <script src="~/plugins/toastr/toastr.min.js" asp-append-version="true" async></script>    *@
    <script src="~/plugins/bs-stepper/js/bs-stepper.min.js" asp-append-version="true" async></script>
    <script src="~/plugins/sweetalert2/sweetalert2.js" asp-append-version="true" async></script>
    <script src="~/js/site.js" asp-append-version="true" async></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MTAdmin.Web/Areas/Archone/Views/Shared/_LoginPageLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin | Log in</title>
    @*<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">*@
    <environment names="Development">
        <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css" asp-append-version="true">
        <!--<link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">-->
        <link rel="stylesheet" href="~/admin-lte/css/adminlte.min.css" asp-append-version="true">
    </environment>   
    <environment names="Production">
        <!--Use CDN here-->
    </environment>
</head>
<body class="hold-transition login-page">
    @RenderBody()
    <environment names="Development">
        <script src="~/plugins/jquery/jquery.min.js" asp-append-version="true"></script>
        <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
        <script src="~/admin-lte/js/adminlte.min.js" asp-append-version="true"></script>
    </environment>
    <environment names="Production">
        <!--Use CDN here-->
    </environment>
    @await Html.PartialAsync("_ValidationScriptsPartial.cshtml")
</body>
</html>

MTAdmin.Web/Areas/Archone/Views/Shared/_SidebarNav.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="index3.html" class="brand-link">
        <span class="brand-text font-weight-light">Admin</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Language" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>Languages</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>Categories</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Tag" asp-action="Index" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Tags</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Template" asp-action="Index" class="nav-link">
                        <i class="nav-icon far fa-image"></i>
                        <p>Templates</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Contact" asp-action="Index" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Enquiries</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="EmailSubscribers" asp-action="Index" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Email Subscriber</p>
                    </a>
                </li>
            </ul>
        </nav>

    </div>

</aside>